/**
 * source-map.js
 * Developer-facing source-of-truth map for screen render ownership and shared UI duplication hotspots.
 */

export const APP_SOURCE_MAP = {
  assetRegistry: {
    primaryRegistryFile: "assets.js",
    planningRegistryFile: "asset-registry.js",
    purpose: "Keep runtime asset ids in assets.js and track usage/duplication cleanup in asset-registry.js before broader migration work.",
    nextMigrationFocus: "rewardArt",
  },
  screens: {
    home: {
      id: "start-screen",
      routeKey: "START",
      primaryFiles: ["index.html", "home-screen.js", "render-home.js", "screen-navigation.js"],
      renderFunctions: ["initHomeScreen", "renderHomeScreen", "showScreen"],
      childAreas: ["home header", "intro panel", "modes menu", "stats/profile entry buttons"],
    },
    lesson: {
      id: "quiz-screen",
      routeKey: "LESSON",
      primaryFiles: ["index.html", "lesson-screen.js", "render-lesson.js", "lesson-flow.js", "screen-navigation.js"],
      renderFunctions: ["initLessonScreen", "renderLessonScreen", "renderLessonAnswerState", "createLessonFlow", "showScreen"],
      childAreas: ["top action buttons", "lesson status bar", "lesson flow panel", "reward bar", "question/options area"],
    },
    sentences: {
      id: "sentences-screen",
      routeKey: "SENTENCES",
      primaryFiles: ["index.html", "sentence-game-wiring.js", "script.js", "screen-navigation.js"],
      renderFunctions: ["createSentenceFilterControls", "renderSentencesRewardStrip", "showScreen"],
      childAreas: ["top action buttons", "status bar", "reward strip", "tts controls", "sentences list"],
    },
    qaGame: {
      id: "qa-game-screen",
      routeKey: "QA_GAME",
      primaryFiles: ["index.html", "qa-flow.js", "qa-wiring.js", "screen-navigation.js"],
      renderFunctions: ["createQaFlow", "createQaControls", "showScreen"],
      childAreas: ["top action buttons", "QA runtime status bar", "round panel", "word bank", "help/sentences modal"],
    },
    sentenceGame: {
      id: "sentence-game-screen",
      routeKey: "SENTENCE_GAME",
      primaryFiles: ["index.html", "sentence-game-wiring.js", "sentence-runtime.js", "sentence-game-reward-manager.js", "screen-navigation.js"],
      renderFunctions: ["createSentenceGameControls", "createSentenceRuntime", "createSentenceGameRewardManager", "showScreen"],
      childAreas: ["top action buttons", "status bar", "reward row/banner", "builder controls", "tip/audio panel"],
    },
    boardEntry: {
      id: "board-game-intro-screen",
      routeKey: "CHAPTER_COVER",
      primaryFiles: ["index.html", "chapter-cover-screen.js", "screen-navigation.js"],
      renderFunctions: ["initChapterCoverScreen", "setPreview", "syncSelectorUi", "showScreen"],
      childAreas: ["cover art", "entry panel", "world selector", "difficulty selector"],
    },
    board: {
      id: "board-game-screen",
      routeKey: "BOARD",
      primaryFiles: ["index.html", "board-screen.js", "render-board.js", "board-runtime.js", "screen-navigation.js"],
      renderFunctions: ["initBoardScreen", "renderBoardScreen", "renderBoardMeta", "renderBoardChallenge", "showScreen"],
      childAreas: ["board top bar", "story panel", "challenge panel", "dice/roll controls", "feedback hub"],
    },
    stats: {
      id: "stats-screen",
      routeKey: "STATS",
      primaryFiles: ["render-shell.js", "stats-screen.js", "progress-ui.js", "screen-navigation.js"],
      renderFunctions: ["mountAppShell", "initStatsScreen", "createProgressUi", "showScreen"],
      childAreas: ["exit row", "progress summary", "time KPI blocks", "reward tabs/cards"],
    },
    rewardAreas: {
      id: "cross-screen-rewards",
      routeKey: "REWARD_SYSTEM",
      primaryFiles: ["render-rewards.js", "progress-ui.js", "sentence-game-reward-manager.js", "render-shell.js", "index.html"],
      renderFunctions: ["renderRewards", "renderRewardStripTiles", "renderLinearRewardBar", "renderSentencesRewardStrip", "createTimedRewardTrack", "createSentenceGameRewardManager"],
      childAreas: ["lesson reward bar", "sentences reward strip", "sentence game reward row/banner", "QA reward bar", "stats reward cards", "profile reward snapshot"],
    },
  },
  sharedUiBlocks: {
    topActionButtons: {
      label: "Top action buttons",
      appearsOnScreens: ["lesson", "sentences", "sentenceGame", "qaGame", "stats", "profile", "end"],
      currentRenderPaths: [
        "index.html -> #quiz-screen .top-action-buttons",
        "index.html -> #sentences-screen .top-action-buttons",
        "index.html -> #sentence-game-screen .top-action-buttons",
        "index.html -> #qa-game-screen .top-action-buttons",
        "render-shell.js -> #stats-screen .play-exit-row",
        "render-shell.js -> #profile-screen .panel-header",
        "render-shell.js -> #end-screen .panel-header",
      ],
      currentFiles: ["index.html", "render-shell.js", "standardized-labels.js", "app-dom.js"],
      duplicationStatus: "duplicated",
      recommendedSourceOfTruth: "shared-ui/learning-top-actions.js or a render-shell fragment factory used by index.html + shell-mounted screens",
      riskNotes: [
        "Highest-risk duplicate: exit/time/vault/save/sound controls drift across lesson, sentences, sentence game, QA, and shell screens.",
        "Standardized labels already exist in standardized-labels.js, which makes this the safest first extraction target.",
      ],
    },
    statusBar: {
      label: "Status bar",
      appearsOnScreens: ["lesson", "sentences", "sentenceGame", "qaGame"],
      currentRenderPaths: [
        "index.html -> #topbar .game-status-bar[data-game-status='lesson']",
        "index.html -> #sentences-screen .game-status-bar[data-game-status='sentences']",
        "index.html -> #sentence-game-screen .game-status-bar[data-game-status='sentence-game']",
        "index.html -> #qa-runtime-status-bar",
      ],
      currentFiles: ["index.html", "app-dom.js", "script.js", "qa-flow.js"],
      duplicationStatus: "duplicated with QA-specific wrapper",
      recommendedSourceOfTruth: "app-dom.js selector registry + shared status-bar renderer/helper",
      riskNotes: [
        "QA status markup is not structurally identical to the learning-status-shell used elsewhere.",
        "qa-flow.js performs runtime normalization/removal of progress-like nodes, so extraction needs explicit QA adapter hooks.",
      ],
    },
    rewardPanel: {
      label: "Reward panel / time-reward area",
      appearsOnScreens: ["lesson", "sentences", "sentenceGame", "qaGame", "stats", "profile"],
      currentRenderPaths: [
        "index.html -> #lesson-reward-bar",
        "index.html -> #sentences-reward-strip",
        "index.html -> #sentence-game-reward-row + #sentence-game-reward-banner",
        "script.js -> qa reward bindings via qaRewardBarEl/qaRewardImageEls",
        "progress-ui.js -> stats reward cards",
        "render-shell.js -> stats/profile reward containers",
      ],
      currentFiles: ["index.html", "render-rewards.js", "progress-ui.js", "sentence-game-reward-manager.js", "render-shell.js", "script.js"],
      duplicationStatus: "partially duplicated / partially shared",
      recommendedSourceOfTruth: "render-rewards.js + reward panel config per mode, with sentence-game banner kept as a mode-specific adapter",
      riskNotes: [
        "Shared reward logic exists, but the DOM contract differs by screen.",
        "Sentence game owns its own reward manager while lesson/sentences rely more directly on shared helpers.",
      ],
    },
    audioControlPanel: {
      label: "Audio/control panel",
      appearsOnScreens: ["sentences", "sentenceGame", "qaGame", "profile", "end"],
      currentRenderPaths: [
        "index.html -> .sentences-top-controls",
        "index.html -> #sentence-game-tip-panel",
        "index.html -> .qa-learning-tools",
        "render-shell.js -> shell sound toggle buttons",
      ],
      currentFiles: ["index.html", "audio-wiring.js", "sentence-game-wiring.js", "qa-wiring.js", "render-shell.js", "standardized-labels.js"],
      duplicationStatus: "partially duplicated",
      recommendedSourceOfTruth: "shared learning utility controls module with per-screen config",
      riskNotes: [
        "Controls are conceptually related but not yet structurally identical.",
      ],
    },
    lessonFlowPanel: {
      label: "Lesson flow panel",
      appearsOnScreens: ["lesson"],
      currentRenderPaths: ["index.html -> .lesson-flow-panel", "render-lesson.js -> lesson answer state", "lesson-flow.js -> flow state"],
      currentFiles: ["index.html", "render-lesson.js", "lesson-flow.js"],
      duplicationStatus: "already somewhat shared",
      recommendedSourceOfTruth: "lesson-flow.js + render-lesson.js",
      riskNotes: [
        "Use this as the reference owner for lesson flow; do not generalize during the mapping step.",
      ],
    },
    titleTimeChipArea: {
      label: "Top title/time chip area",
      appearsOnScreens: ["lesson", "sentences", "sentenceGame", "end", "stats/profile partials"],
      currentRenderPaths: [
        "index.html -> #quiz-screen .learning-header-row",
        "index.html -> #sentences-screen .learning-header-row",
        "index.html -> #sentence-game-screen .learning-header-row",
        "render-shell.js -> #end-screen .time-widget",
      ],
      currentFiles: ["index.html", "render-shell.js", "app-dom.js", "script.js"],
      duplicationStatus: "partially duplicated",
      recommendedSourceOfTruth: "shared header-row fragment alongside the future status-bar renderer",
      riskNotes: [
        "QA does not use the same title/time row, so it should join later through an adapter rather than forcing exact parity.",
      ],
    },
    utilityRowsAndButtons: {
      label: "Repeated utility rows/buttons",
      appearsOnScreens: ["lesson", "sentences", "sentenceGame", "qaGame"],
      currentRenderPaths: [
        "index.html -> learning-master-row blocks across lesson/sentences/sentence-game/QA",
        "index.html -> sentences/QA/sentence-game support control groups",
        "standardized-labels.js -> cross-screen button label normalization",
      ],
      currentFiles: ["index.html", "standardized-labels.js", "script.js", "audio-wiring.js", "sentence-game-wiring.js", "qa-wiring.js"],
      duplicationStatus: "duplicated / partially duplicated",
      recommendedSourceOfTruth: "shared row renderer with per-screen config objects for level pickers and auxiliary tools",
      riskNotes: [
        "Sentence vs QA vs quiz control structures use the same grouping idea but with mismatched wrappers and control inventories.",
      ],
    },
  },
  renderSources: {
    domRegistry: ["app-dom.js"],
    screenLifecycle: ["home-screen.js", "lesson-screen.js", "chapter-cover-screen.js", "board-screen.js", "stats-screen.js"],
    navigation: ["screen-navigation.js"],
    shellMountedMarkup: ["render-shell.js"],
    staticMarkup: ["index.html"],
  },
  recommendedUnificationOrder: [
    "topActionButtons",
    "statusBar",
    "titleTimeChipArea",
    "rewardPanel",
    "utilityRowsAndButtons",
    "audioControlPanel",
  ],
  riskyDuplicateAreas: [
    {
      area: "Top action buttons",
      why: "Exit/time/vault/save/sound controls are repeated with near-identical markup across lesson, sentences, sentence game, QA, and shell-mounted screens.",
      files: ["index.html", "render-shell.js", "standardized-labels.js", "app-dom.js"],
      priority: 1,
    },
    {
      area: "QA status area and runtime wrappers",
      why: "QA has a custom runtime status shell plus cleanup logic in qa-flow.js, while other learning screens hardcode similar status bars in index.html.",
      files: ["index.html", "qa-flow.js", "app-dom.js", "script.js"],
      priority: 2,
    },
    {
      area: "Reward and time-reward UI",
      why: "Reward tiles/rows are partly hardcoded in HTML and partly rendered by shared reward helpers, increasing drift risk across learning modes and stats.",
      files: ["index.html", "render-rewards.js", "progress-ui.js", "sentence-game-reward-manager.js", "script.js"],
      priority: 3,
    },
    {
      area: "Sentence vs QA vs quiz duplicated control structures",
      why: "Learning control groups follow the same conceptual layout but use different wrappers, level pickers, and helper rows that will complicate unification.",
      files: ["index.html", "sentence-game-wiring.js", "qa-wiring.js", "audio-wiring.js"],
      priority: 4,
    },
  ],
};
